#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use App\Command\FetchFramesCommand;
use Symfony\Component\Console\Application;

$application = new Application('epic-seasons', '1.0.0');
$command = new FetchFramesCommand();

$application->add($command);

$application->setDefaultCommand($command->getName(), true);
$application->run();
